#!/bin/bash

usage=$(cat <<EOF
Spacemaracas - the beginnings of a vnc emacs thing with lazy documentation

Usage:
$0 run -- just run the thing. Will pull images if they are not built.
$0 stop -- stop the running application
$0 build -- Build images from source (more recent, less stable)
$0 clean -- Delete the Docker containers left around after running
$0 help -- Display this help screen
EOF
     )


cd local
if test $# -eq 0; then
    echo "$usage"
    exit 0
fi

while test $# -gt 0
do
    case "$1" in
        build) ./build.sh
               ;;
        run) ./run.sh
             ;;
        stop) ./clean.sh
              ;;
        publish) ./publish.sh
                 ;;
        vnc-only) docker run -d --name some-emacs -p 5900:5900 gigawhitlocks/emacs:latest
                  ;;
        *) echo "$usage"
           ;;
    esac
    shift
done

exit 0
